const GLOBAL_START = '@GLOBAL_AUTH//START'
const GLOBAL_LOGOUT = '@GLOBAL_AUTH//LOGOUT'
const GLOBAL_SUCCESS = '@GLOBAL_AUTH//SUCCESS'
const GLOBAL_FAILURE = '@GLOBAL_AUTH//FAILURE'

const GLOBAL_SIGN_IN_SAGA = '@GLOBAL_AUTH/*saga*/SIGN_IN'
const GLOBAL_FB_LOGIN_SAGA = '@GLOBAL_AUTH/*saga*/FB_LOGIN'
const GLOBAL_GOOGLE_LOGIN_SAGA = '@GLOBAL_AUTH/*saga*/GOOGLE_LOGIN'

export const GLOBAL_TYPES = {
  GLOBAL_START,
  GLOBAL_LOGOUT,
  GLOBAL_SUCCESS,
  GLOBAL_FAILURE,
  GLOBAL_SIGN_IN_SAGA,
  GLOBAL_FB_LOGIN_SAGA,
  GLOBAL_GOOGLE_LOGIN_SAGA
} as const
